
# @url  = http://localhost:3001/api
@url  = https://cmshotel.onrender.com/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcl9uYW1lIjoia2hvYXZoIiwiZW1haWwiOiJodXlraG9hNjMwQGdtYWlsLmNvbSIsImlhdCI6MTY3OTUzOTAyNiwiZXhwIjoxNjc5NTQyNjI2fQ.QmQQ5bRtQKIcgk1X671eJnl1H_u0aRxeqAr7zCl_4R0s

@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcl9uYW1lIjoia2hvYXZoIiwiZW1haWwiOiJodXlraG9hNjMwQGdtYWlsLmNvbSIsImlhdCI6MTY3OTUzODgwOCwiZXhwIjoxNjc5NTQyNDA4fQ.UjHK0rDUCTRnbk6m6aBMF0N1VDNVWfOAV6OD5q0URVE
# =============AUTH================== 

### Register
POST {{url}}/auth/register
Content-Type: application/json

{
    "user_name": "khoavh",
    "email" : "huykhoa630@gmail.com",
    "password": "1",
}

### Login
POST {{url}}/auth/login
Content-Type: application/json

{
    "user_name": "khoavh",
    "password": "1"
}

### Logout
POST {{url}}/auth/logout
Content-Type: application/json

{
    "id": "2"
}

### refreshToken
POST {{url}}/auth/refreshtoken
Content-Type: application/json

{
    "id": 2,
    "refresh_token": "{{refresh_token}}"
}

# ==================USER=========================

###  User List
GET {{url}}/user
Authorization: Beaer {{token}}
Content-Type: application/json

###  User Create
POST {{url}}/user/create
Authorization: Beaer {{token}}
Content-Type: application/json

{
    "user_name": "tungson",
    "full_name": "tung son",
    "email": "huykhoa630@gmail.com",
    "password": "1",
    "identity_number": "2006444928",
    "phone": "0977425396",
    "role": "1"
}

###  User Update
PUT {{url}}/user/update
Authorization: Beaer {{token}}
Content-Type: application/json

{
    "id": "7",
    "user_name": "be anh",
    "full_name": "a",
    "email": "huykhoa630@gmail.com",
    "password": "1",
    "identity_number": "2006444928",
    "phone": "0977425396",
    "role": "1"
}

### Migration USer
GET {{url}}/migration/user

### Drop USer
GET {{url}}/drop/user

### Seeder USer
GET {{url}}/seeder/user


